name: Docker Image CI
on:
  push:
    branches:
      - master  # Triggers on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: 
                rexmyapp/mycustomrepo:latest
                rexmyapp/mycustomrepo:${{ github.sha }}

      # Verify the Docker image (Optional)
      - name: Docker image digest
        run: echo "Image digest: ${{ steps.docker_build.outputs.digest }}"
